// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: feeds.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFeeed = `-- name: CreateFeeed :one
INSERT INTO feeds (name, url, user_id)
VALUES($1, $2, $3)
RETURNING name, url, user_id
`

type CreateFeeedParams struct {
	Name   string    `json:"name"`
	Url    string    `json:"url"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateFeeed(ctx context.Context, arg CreateFeeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeeed, arg.Name, arg.Url, arg.UserID)
	var i Feed
	err := row.Scan(&i.Name, &i.Url, &i.UserID)
	return i, err
}
